version: "3.9"

services:
  mangotango-web: # Do not forget to modfy .env!
    hostname: mangotango-web
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - nginx-network

  mangotango-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: mangotango-api
    environment:
      - RCON_HOST=minecraft-server-host
      - RCON_PORT=25575
      - RCON_PASS=password
      - SERVER_DATA_PATH=/var/minecraft
      - CORS_ORIGIN=https://full-uri
    volumes:
      - minecraft-data:/var/minecraft # Binding so we can find whitelist.json
    networks: # Requires manually adding to bridge.
      - nginx-network
      - minecraft-network 

networks:
  nginx-network:
    external: true
    name: nginx # your web network
  minecraft-network:
    external: true
    name: minecraft

volumes:
  minecraft-data:
    external: true
    name: minecraft #Volume name of your external volume
