version: "3.9"

services:
  mangotango-web: # Do not forget to modfy .env!
    hostname: mangotango-web
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - nginx-network

  mangotango-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: mangotango-api
    environment:
      - RCON_HOST=minecraft-server-host # CHANGEME This is the hostname or IP for your minecraft server's RCON
      - RCON_PORT=25575 # CHANGEME Your RCON port
      - RCON_PASS=password # CHANGEME Your RCON password
      - CORS_ORIGIN=https://full-uri # CHANGEME The surface web url you'll use for your front end.
      - BASE_PATH=/ # Base path for your API. Change this if your API is not served on the root path.
      - SERVER_DATA_PATH=/var/minecraft # You probably wouldn't want to modify this. We're mapping this to a volume.
      - FLOODGATE_PREFIX=. # Change this if your prefix differs.
      #- OPENXBL_KEY= #Add if you want to use OpenXBL as XUID resolver fallback
    volumes:
      - minecraft-data:/var/minecraft # Binding to minecraft data directory so we can find whitelist.json
    networks: # Requires manually adding to bridge.
      - nginx-network
      - minecraft-network 

networks:
  nginx-network:
    external: true
    name: nginx # CHANGEME Your reverse proxy's network
  minecraft-network:
    external: true
    name: minecraft # CHANGEME Your minecraft server's network

volumes:
  minecraft-data:
    external: true
    name: minecraft # CHANGEME Volume name of your minecraft data volume
