version: "3.9"

services:
  mangotango-web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: mangotango-web
    environment:
      - REACT_APP_API_ENDPOINT=http://whitelist-api # Points to your web-facing endpoint
      - REACT_APP_NAME="My Server"
      - REACT_APP_DESCRIPTION="Whitelisted SMP"
      - REACT_APP_MINECRAFT_IP=173.212.202.108 # Only for display on the web page
    networks:
      - nginx-network

  mangotango-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: mangotango-api
    environment:
      - RCON_HOST=173.212.202.108
      - RCON_PORT=25575
      - RCON_PASS=password
      - SERVER_DATA_PATH=/var/minecraft
    volumes:
      - minecraft-data:/var/minecraft # Binding so we can find whitelist.json
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
    name: nginx # your web network

volumes:
  minecraft-data:
    external: true
    name: minecraft #Volume name of your external volume
